apiVersion: v1
kind: Service
metadata:
  name: xray-ui
  namespace: xray
  labels:
    app: xray-ui
spec:
  type: ClusterIP
  ports:
    - name: web-ui
      port: 2053
      protocol: TCP
  selector:
    app: xray-ui
---
apiVersion: v1
kind: Service
metadata:
  name: xray-sub
  namespace: xray
  labels:
    app: xray-sub
spec:
  type: ClusterIP
  ports:
    - name: web-sub
      port: 2096
      protocol: TCP
  selector:
    app: xray-ui
---
apiVersion: v1
kind: Service
metadata:
  name: xray-vpn
  namespace: xray
  labels:
    app: xray-vpn
spec:
  type: NodePort
  ports:
    - name: xray-vless
      port: 31002
      targetPort: 31002
      nodePort: 31002
      protocol: TCP
  selector:
    app: xray-ui
