resources:
  - mail
  - authelia
  - cert-manager
#  - https://raw.githubusercontent.com/reactive-tech/kubegres/v1.15/kubegres.yaml
#  - github.com/kubenav/deploy/kustomize
  - nfs-provisioner.yaml
  - sealed-secrets
